<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.2.1.352
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Produtos Formulário envio',
	'heading' => 'Envio de novo formulário',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Marcado',
		'checkbox_unchecked' => 'Desmarcado',
		'submitted_from' => 'Formulário enviado do site: %s',
		'submitted_by' => 'Endereço IP do visitante: %s',
		'too_many_submissions' => 'Muitos envios recentes deste IP',
		'failed_to_send_email' => 'Falha no envio do email',
		'invalid_reCAPTCHA_private_key' => 'Chave privada do reCAPTCHA inválida.',
		'invalid_field_type' => 'Tipo de campo desconhecido \"%s\".',
		'invalid_form_config' => 'O campo \"%s\" possui uma configuração inválida.',
		'unknown_method' => 'Método de solicitação de servidor desconhecido'
	),
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U128' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nome do produto',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Nome do produto\" é obrigatório.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Código do Produto',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Código do Produto\" é obrigatório.',
				'format' => 'O campo \"Código do Produto\" possui um email inválido.'
			)
		),
		'custom_U123' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Tipo',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Tipo\" é obrigatório.'
			)
		),
		'custom_U141' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Quantidade',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Quantidade\" é obrigatório.'
			)
		),
		'custom_U150' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Descrição',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Descrição\" é obrigatório.'
			)
		)
	)
);

process_form($form);
?>
